### ISSUE TITLE
 SetuptoolsDeprecationWarning: setup.py install is deprecated.

### ISSUE THREAD

**Issue by tk1** [sunspec/pysunspec2#86]
When trying to install with 

    python .\setup.py install

I get the warning:  SetuptoolsDeprecationWarning: setup.py install is deprecated.

**Comment by ttansy** [comment]
pysunspec needs maintenance.


Tom Tansy
SunSpec Alliance
831-227-1073
***@***.***

**Comment by ttansy** [comment]
Hi Tom,

It seems like the &#39;python setup.py install&#39; has been deprecated. Here&#39;s the article talking about it: https://packaging.python.org/en/latest/discussions/setup-py-deprecated/

I believe we just need to change the Readme on github to state &#39;Use pip install pysunspec2&#39; for installation. That&#39;s the recommended command for installation and it works fine. I will make that change.

Thanks,
Kudrat

Kudrat Kaur
***@***.***

SunSpec Alliance

On Tuesday, January 2nd 2024, 9:35:18 AM ***@***.*** ***@***.***&gt; wrote:

pysunspec needs maintenance.

Tom Tansy
SunSpec Alliance
831-227-1073
***@***.***

On Tue, Jan 2, 2024 at 6:49 AM tk1 ***@***.***&gt; wrote:

When trying to install with

python .\setup.py install

I get the warning:  SetuptoolsDeprecationWarning: setup.py install is deprecated.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;





Desk tracking: [DESK-3b2n-2nqmh]

**Comment by ttansy** [comment]
Sounds good Kudrat. Thanks for making the change.

Let's make a plan for supporting this project. Should we co-opt the Modbus
group once per month?


Tom Tansy
SunSpec Alliance
831-227-1073
***@***.***

**Comment by tk1** [comment]
> Hi Tom, It seems like the &#39;python setup.py install&#39; has been deprecated. 

I installed it via pip, but my intention was to say that the documentation is outdated.

**Comment by Kudrat9** [comment]
Hi @tk1 Thanks for pointing that out. We've updated the Readme to install using pip and mentioned the python setup.py install is deprecated.
